# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
version=3.8-26.2
mod_version=3.8-26.2
maven_group=computer.heather.advancedbackups
archives_base_name=advancedbackups
modloaderName=fabric
minecraftVersion=26.2

# Dependencies
fabric_api_version=0.157.0+26.2
