org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1.2
minecraft_version_range=[26.1,26.2)
neo_version=26.1.2.97

mod_id=advancedbackups
mod_name=Advanced Backups
mod_license=BSD
mod_version=3.8-26.1
mod_group_id=computer.heather.advancedbackups
mod_authors=Heather White
mod_description=A highly advanced and configurable backup mod. Github contains documentation.

modloaderName=neoforge
minecraftVersion=26.1
